---
title: 'Reproducible Research: Peer Assessment 2'
author: "Andrew E. Davidson"
date: "September 23, 2015"
output: html_document
---

## Download data and documentation, and load data 
```{r load data if needed}
fileURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
fileName <- "repdata-data-StormData.csv.bz2"
dataDir <- "data/"
dataFileZip <- sprintf("%s%s", dataDir, fileName)
dataFile <- sprintf("%s%s", dataDir, "repdata-data-StormData.csv")
if (!file.exists(dataDir)) { dir.create(dataDir)}
if (!file.exists(dataFile)) {
  download.file(fileURL, destfile=dataFileZip, method="curl")
  dateDownLoaded <- date()
  write(dateDownLoaded, file=sprintf("%s%s", dataDir, "dateDownLoaded.txt"))
  
  library(R.utils)
  bunzip2(dataFileZip)
}

fileURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf"
fileName <- "stormDataDocumentation.pdf"
docFile <- sprintf("%s%s", dataDir, fileName)
if (!file.exists(docFile)) {
  download.file(fileURL, destfile=docFile, method="curl")
}

fileURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf"
fileName <- "FAQ.pdf"
faqFile <- sprintf("%s%s", dataDir, fileName)
if (!file.exists(faqFile)) {
  download.file(fileURL, destfile=faqFile, method="curl")
}

library(data.table)
if (!exists("dTable")){
    # line 54 did not have two elements, fill should fix this for us
    csv <- read.csv(dataFile, header=TRUE, fill=TRUE)
    dTable <- data.table(csv)
}

#clean up. Temporarly turn off warnings about missing objects not found
options(warn=-1) 
rm(csv, dataDir, dataFile, dataFileZip, dateDownLoaded, docFile, faqFile, fileName, fileURL)
options(warn=0) 

```

## Question 1:
Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?


```{r use tables}
q1Data <- dTable[, list(EVTYPE, HARM = FATALITIES + INJURIES)]
q1AggregatedData <- q1Data[, list(TOTAL_HARM=sum(HARM)), by=EVTYPE]
q1OrderedData <- q1AggregatedData[order(TOTAL_HARM, decreasing=TRUE),]
nrow(q1OrderedData[TOTAL_HARM != 0])
```

```{r q1 graph}
library(ggplot2)

q1Graph <- qplot(
    y=TOTAL_HARM, x=EVTYPE, stat="identity", data=q1OrderedData[1:10,], 
    geom="bar", fill=factor(EVTYPE), 
    main="10 Most Harmfull Storm Types to Public Health")

q1Graph + theme(axis.text.x=element_blank())
q1OrderedData[1:10,]
```

## AED hacks
length(unique(dTable[,EVTYPE]))
dt <- data.table(a=1:2, b=2:3, c=3:4)
dt[, (b, c)]

```{r q1: table is converted back to data frame}
x <- dTable[, list(EVTYPE,FATALITIES, INJURIES)]
y <- x[, list(EVTYPE, HARM=FATALITIES + INJURIES)]
a <- aggregate(. ~ EVTYPE, data=y, FUN=sum)
o <- a[order(a$HARM, decreasing=TRUE),]

# select events that have harmed people
h<-o[o$HARM != 0,]
nrow(h)
```
## Question 2:
Across the United States, which types of events have the greatest economic consequences?

```{r}
dTable[1:10, list(PROPDMG, PROPDMGEXP, AEDWIP=(PROPDMG * 2)]
dTable[1:10, list(PROPDMG, PROPDMGEXP, AEDWIP=(PROPDMG * 2), A2=as.numeric(levels(PROPDMGEXP),PROPDMGEXP)]

a <- dTable[PROPDMGEXP == "K", list(PROPDMG,PROPDMGEXP)]
nrow(a)

b <- dTable[PROPDMGEXP == "K" | PROPDMGEXP == "M", list(PROPDMG,PROPDMGEXP)]
nrow(b)

c <- dTable[PROPDMGEXP == "K" | PROPDMGEXP == "M" | PROPDMGEXP == "B", list(PROPDMG,PROPDMGEXP)]
nrow(c)

# this selects rows where we have good property damage data
d <- dTable[PROPDMGEXP == "K" | PROPDMGEXP == "k" | PROPDMGEXP == "M" | PROPDMGEXP == "m" | PROPDMGEXP == "B" | PROPDMGEXP == "b", list(PROPDMG,PROPDMGEXP)]
nrow(d)

# this selects rows where we have good crop damage data
e <- dTable[CROPDMGEXP == "K" | CROPDMGEXP == "k" | CROPDMGEXP == "M" | CROPDMGEXP == "m" | CROPDMGEXP == "B" | CROPDMGEXP == "b", list(CROPDMG,CROPDMGEXP)]
nrow(e)

```
